# Dynamic configuration for Traefik
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"

  routers:
    # Global HTTP to HTTPS redirect
    http-catchall:
      rule: "hostregexp(`{host:.+}`)"
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
      service: api@internal
